x1=input("Digite algo:")
print("O tipo primitivo é",type(x1))
print("So têm espaços?",x1.isspace())
print("Há letras ou números?",x1.isalnum())
print("Há letras?",x1.isalpha())
print("Possui apenas letras maiúsculas?",x1.isupper())
print("possui apenas letras minúsculas?",x1.islower())
print("Está capitalizada",x1.istitle())
